openapi: 3.0.0
tags:
  - name: Tasks
    description: API operations related to tasks
x-stoplight:
  id: mr7b6i51sz5jz
info:
  title: Template
  version: '1.0'
  description: endpoint list for task
  license:
    name: Your License Name
    url: 'https://example.com/license'
  contact:
    name: Your Name
    email: your.email@example.com
    url: example.com
servers:
  - url: 'http://localhost:3000'
paths:
  '/tasks/{taskId}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: taskId
        in: path
        description: existing task id to be find
        required: true
    get:
      summary: Get specific task by id
      responses:
        '200':
          description: Shared Response
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    x-stoplight:
                      id: js9kqzluwjfsm
                    properties:
                      data:
                        $ref: '#/components/schemas/Task'
                  - $ref: '#/components/schemas/BaseResponse'
        '500':
          description: Shared Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              examples:
                Example 1:
                  value:
                    message: string
                    timestamp: 0
                    process_time: 0
      operationId: get-tasks-taskId
      x-stoplight:
        id: prpnh1qb55b0m
      parameters: []
      description: Get specific task by task_id
    put:
      summary: Update task
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
      operationId: put-tasks-taskId
      x-stoplight:
        id: 32f6cdw3m8gpd
      requestBody:
        description: task properties to update
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  x-stoplight:
                    id: 322im5im2rp9n
            examples:
              Example 1:
                value:
                  title: title baru
      description: Update task detail
    delete:
      summary: Delete task
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
      operationId: delete-tasks-taskId
      x-stoplight:
        id: sko8a94iuvm2q
      description: delete task endpoint
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: Shared Response
          content:
            application/json:
              schema:
                allOf:
                  - x-stoplight:
                      id: jk5w0b2s4svyc
                    type: object
                    properties:
                      data:
                        type: array
                        x-stoplight:
                          id: fwl3vg06ua67i
                        items:
                          $ref: '#/components/schemas/Task'
                  - $ref: '#/components/schemas/BaseResponse'
              examples:
                Example 1:
                  value:
                    message: success
                    timestamp: 1707190114
                    process_time: 130
                    data:
                      - id: 1
                        title: write timesheet
                        status: 1
                      - id: 2
                        title: daily standup
                        status: 0
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              examples:
                Example 1:
                  value:
                    response_header:
                      success: false
                      message: error getting tasks
                      process_time: 0
      operationId: get-tasks
      x-stoplight:
        id: jc08h943txlln
      description: 'Get '
    post:
      summary: Create task
      operationId: post-tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              examples:
                Example 1:
                  value:
                    message: success
                    timestamp: 1707190114
                    process_time: 150
            application/xml:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
              examples:
                Example 1:
                  value:
                    message: error
                    timestamp: 1707190114
                    process_time: 210
      x-stoplight:
        id: kho6ygmj03lrq
      description: Add Task
      parameters: []
      requestBody:
        description: Request to add task
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                title:
                  type: string
                  x-stoplight:
                    id: pqewevjrncqwg
            examples:
              Example 1:
                value:
                  title: task 1
components:
  schemas:
    Task:
      title: Task
      x-stoplight:
        id: semgxfb01vwc6
      type: object
      description: Model for task
      properties:
        id:
          type: integer
          x-stoplight:
            id: fk9wikxdne1m4
          format: int64
        title:
          type: string
          x-stoplight:
            id: z4igsrq585cms
        status:
          type: integer
          x-stoplight:
            id: fhplzavszdw70
    BaseResponse:
      title: Base Response
      x-stoplight:
        id: obfvmj6b6dcwi
      type: object
      x-examples: {}
      properties:
        message:
          type: string
          x-stoplight:
            id: 2vxmyrpppy1b1
        timestamp:
          type: integer
          x-stoplight:
            id: zxd0klb8snan2
        code:
          type: string
          x-stoplight:
            id: mwd2oquilqq2r
  responses: {}
x-internal: false
