openapi: 3.0.0
x-stoplight:
  id: hv9aajgmhu4sd
info:
  title: Template
  version: "1.0"
  description: endpoint list for task
servers:
  - url: "http://localhost:3000"
paths:
  /tasks:
    get:
      summary: Get all tasks
      tags: []
      responses:
        "200":
          description: Task created
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    status:
                      type: integer
                x-examples:
                  Example 1:
                    - id: 1
                      title: test
                      status: 1
                    - id: 2
                      title: booo
                      status: 1
              examples:
                Example 1:
                  value:
                    - id: 1
                      title: test
                      status: 1
                    - id: 2
                      title: booo
                      status: 1
      operationId: get-tasks
      x-stoplight:
        id: oqfrdy44c609p
      description: "Get "
    post:
      summary: Create task
      operationId: post-tasks
      responses:
        "200":
          description: OK
      x-stoplight:
        id: mloywbl6oucmp
      description: Add Task
      parameters: []
      requestBody:
        description: Request to add task
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                title:
                  type: string
                  x-stoplight:
                    id: icbplm9w7d1qb
            examples:
              Example 1:
                value:
                  title: task 1
  "/tasks/:{taskId}":
    parameters:
      - schema:
          type: integer
        name: taskId
        in: path
        required: true
        description: existing task id to be find
    get:
      summary: Get specific task by id
      tags: []
      responses:
        "200":
          description: |-
            {
                "id": 1,
                "title": "test",
                "status": 1
            }
      operationId: get-tasks-taskId
      x-stoplight:
        id: a1h8yepfkwlh2
      parameters: []
    put:
      summary: Update task
      tags: []
      responses:
        "200":
          description: |-
            {
                "id": 1,
                "title": "title baru",
                "status": 1
            }
      operationId: put-tasks-taskId
      x-stoplight:
        id: k9z4qowh5iuyu
      requestBody:
        description: task properties to update
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  x-stoplight:
                    id: r8109c3qr0l2f
            examples:
              Example 1:
                value:
                  title: title baru
    delete:
      summary: Delete task
      tags: []
      responses:
        "200":
          description: Success delete task
      operationId: delete-tasks-taskId
      x-stoplight:
        id: 2yfk80l989she
      description: delete task endpoint
components:
  schemas:
    Task:
      title: Task
      x-stoplight:
        id: 6ik83chrljzbx
      type: object
      properties:
        id:
          type: integer
          x-stoplight:
            id: 4jpc8wh7caqgc
        title:
          type: string
          x-stoplight:
            id: lrx0s4fejkav7
        status:
          type: integer
          x-stoplight:
            id: 1ewevm6jvwqhd
      description: Model for task
