// Code generated by mockery v2.39.1. DO NOT EDIT.

package task

import (
	model "base/internal/repository/db/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: title
func (_m *MockRepository) CreateTask(title string) (model.Task, error) {
	ret := _m.Called(title)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.Task, error)); ok {
		return rf(title)
	}
	if rf, ok := ret.Get(0).(func(string) model.Task); ok {
		r0 = rf(title)
	} else {
		r0 = ret.Get(0).(model.Task)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: id
func (_m *MockRepository) DeleteTask(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllTasks provides a mock function with given fields: ctx
func (_m *MockRepository) GetAllTasks(ctx context.Context) ([]model.Task, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Task, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Task); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskByID provides a mock function with given fields: id
func (_m *MockRepository) GetTaskByID(id int) (model.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (model.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) model.Task); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Task)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: id, title
func (_m *MockRepository) UpdateTask(id int, title string) (model.Task, error) {
	ret := _m.Called(id, title)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (model.Task, error)); ok {
		return rf(id, title)
	}
	if rf, ok := ret.Get(0).(func(int, string) model.Task); ok {
		r0 = rf(id, title)
	} else {
		r0 = ret.Get(0).(model.Task)
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(id, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
